import fs from "fs";
import path from "path";
import { config } from "hardhat";

async function main() {
  // Create output directory if it doesn't exist
  const outputDir = path.resolve(__dirname, "../../frontend/src/lib/contracts");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  console.log("Exporting contract ABIs and bytecodes...");

  const artifactsPath = path.resolve(__dirname, "../artifacts");

  // Export PlaygroundERC20
  const erc20Artifact = JSON.parse(
    fs.readFileSync(path.join(artifactsPath, "contracts", "PlaygroundERC20.sol", "PlaygroundERC20.json"), "utf8")
  );

  // Export PlaygroundNFT
  const nftArtifact = JSON.parse(
    fs.readFileSync(path.join(artifactsPath, "contracts", "PlaygroundNFT.sol", "PlaygroundNFT.json"), "utf8")
  );

  // Export TeachingSwapRouter
  const swapRouterArtifact = JSON.parse(
    fs.readFileSync(path.join(artifactsPath, "contracts", "TeachingSwapRouter.sol", "TeachingSwapRouter.json"), "utf8")
  );

  // Write to frontend
  fs.writeFileSync(
    path.join(outputDir, "abis.ts"),
    `// Auto-generated by export-abis.ts

export const PLAYGROUND_ERC20_ABI = ${JSON.stringify(erc20Artifact.abi, null, 2)} as const;
export const PLAYGROUND_NFT_ABI = ${JSON.stringify(nftArtifact.abi, null, 2)} as const;
export const TEACHING_SWAP_ROUTER_ABI = ${JSON.stringify(swapRouterArtifact.abi, null, 2)} as const;
`
  );

   fs.writeFileSync(
    path.join(outputDir, "bytecodes.ts"),
    `// Auto-generated by export-abis.ts

export const PLAYGROUND_ERC20_BYTECODE = "${erc20Artifact.bytecode}" as const;
export const PLAYGROUND_NFT_BYTECODE = "${nftArtifact.bytecode}" as const;
export const TEACHING_SWAP_ROUTER_BYTECODE = "${swapRouterArtifact.bytecode}" as const;
`
  );

  fs.writeFileSync(
    path.join(outputDir, "addresses.ts"),
    `// Pre-deployed contract addresses on Polkadot Hub TestNet (REVM).
// Read actual values through Vite env vars; fall back to zero address.

type HexAddress = \`0x\${string}\`;

export const ZERO_ADDRESS: HexAddress = '0x0000000000000000000000000000000000000000';

const normalizeAddress = (value: string): HexAddress => {
  const formatted = value.trim();
  if (formatted.startsWith('0x') || formatted.startsWith('0X')) {
    return formatted as HexAddress;
  }
  return \`0x\${formatted}\` as HexAddress;
};

const resolveAddress = (envValue?: string): HexAddress => {
  if (!envValue) return ZERO_ADDRESS;
  const normalized = envValue.trim();
  if (normalized.toLowerCase() === ZERO_ADDRESS) return ZERO_ADDRESS;
  return normalizeAddress(normalized);
};

const getEnvValue = (key: 'VITE_PLAYGROUND_NFT_ADDRESS' | 'VITE_TEACHING_SWAP_ROUTER_ADDRESS'): string | undefined => {
  if (typeof import.meta !== 'undefined' && 'env' in import.meta) {
    return (import.meta.env as ImportMetaEnv & Record<string, string | undefined>)[key];
  }

  if (typeof process !== 'undefined') {
    return process.env[key];
  }

  return undefined;
};

export const PLAYGROUND_NFT_ADDRESS = resolveAddress(getEnvValue('VITE_PLAYGROUND_NFT_ADDRESS'));
export const TEACHING_SWAP_ROUTER_ADDRESS = resolveAddress(getEnvValue('VITE_TEACHING_SWAP_ROUTER_ADDRESS'));

export function isConfiguredContractAddress(address: string): boolean {
  return address.toLowerCase() !== ZERO_ADDRESS.toLowerCase();
}
`
  );

  console.log("\n✅ ABIs and bytecodes exported successfully to frontend/src/lib/contracts/");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
